services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: realestate_web

    restart: unless-stopped

    command: gunicorn --bind 0.0.0.0:8000 realestate.wsgi:application

    # env_file:
    #   - .env

    volumes:
      # Mount the entire Django project
      - .:/app

      # User-uploaded files
      - ./media:/app/media

      # Collected static files
      - ./staticfiles:/app/staticfiles

    expose:
      - "8000"

    labels:
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.realestate.rule=Host(`realestate.atongjona.com`)"
      - "traefik.http.routers.realestate.entrypoints=https"
      - "traefik.http.routers.realestate.tls=true"
      - "traefik.http.routers.realestate.tls.certresolver=le"

      # Django/Gunicorn service
      - "traefik.http.services.realestate.loadbalancer.server.port=8000"

      # Tell Traefik which Docker network to use
      - "traefik.docker.network=traefik"

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true