# Generated by Django 6.1 on 2026-09-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size_sqm', models.PositiveIntegerField(blank=True, help_text='Size / plinth area in sqm', null=True)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('luxury', 'Luxury'), ('other', 'Other')], default='apartment', max_length=32)),
                ('is_ready_unit', models.BooleanField(default=False)),
                ('is_offplan', models.BooleanField(default=False)),
                ('available_for_sale', models.BooleanField(default=True)),
                ('available_for_rent', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('instalment_period_months', models.PositiveIntegerField(blank=True, help_text='Instalment period in months', null=True)),
                ('estimated_roi_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('units', models.PositiveIntegerField(blank=True, help_text='Number of units (if part of a development)', null=True)),
                ('towers', models.PositiveIntegerField(blank=True, help_text='Number of towers (if part of a development)', null=True)),
                ('amenities', models.TextField(blank=True, help_text='Comma or newline separated amenities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
